name: Github actions contexts
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: get github actions context
              run: echo "${{toJson(github)}}"
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: get environnement variables
              run: echo "${{toJson(env)}}"
