name: Github actions contexts
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: get github actions context
              run: echo "${{github}}"